### PR TITLE
Add git_is_tag function and its appropriate tests

### PR DESCRIPTION
**Pull request by stefanmaric**
The git_is_tag functions checks if the HEAD ref points to a tag; it can
be a simple, annotated or signed tag.

When checking out a tag, you enter in "detached head" mode, for that
reason I'm using the git_is_detached_head function in here.

This is useful in use with the git_branch_name function, which returns
the tag name if HEAD points to one. I'm using it on my prompt to
display a diff icon when on top of a tag: https://git.io/vX4Ku

### CODE REVIEW

**Comment by stefanmaric** [comment]
Tests are failing but not due these changes, instead:

```
not ok 1 git_branch_name - Get the name of the current Git branch
```

On my Ubuntu 16.04 system using fish  `2.3.1` and git `2.7.4` from Ubuntu's repos, all the test are passing.

**Comment by stefanmaric** [comment]
I added forgotten reference to the `is_tag_function` inside README.md

@jbucaran can you take a look on travis build? I think the base branch would need some tweaks.

Regards!

**Comment by jbucaran** [comment]
Hey @stefanmaric and thanks for this addition! I think the problem is git_branch_name behaving strangely on Travis. I'll merge now and see what happens.

**Comment by jbucaran** [comment]
@stefanmaric One more thing. I had to rebase the history to change it to use my new email. You'll need to pull with force to sync with master, or just clone the repo again if you'd like to contribute again later.

Cheers!

**Comment by stefanmaric** [comment]
> I think the problem is git_branch_name behaving strangely on Travis.

Indeed!

> You'll need to pull with force to sync with master, or just clone the repo again if you'd like to contribute again later.

Gotcha!

Thanks! Regards!

**Pull request merged**
